Hw13 calendar
Tyrqvir/otus_hw pull request #15
Opened 2022-10-16 20:11 UTC by Tyrqvir

## Домашнее задание №13 «API к Календарю»

### Критерии оценки
- [ ] Makefile заполнен и пайплайн зеленый - 1 балл
- [ ] Реализовано GRPC API и `make generate` - 3 балла
- [ ] Реализовано HTTP API - 2 балла
- [ ] Написаны юнит-тесты на API - до 2 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2022-10-31 09:54 UTC, dshemin requested changes

2022-10-31 09:54 UTC, dshemin commented on hw12_13_14_15_calendar/api/EventService.proto
> +  Event event = 1;
Будет лучше перечислить конкретные поля, который можно установить. Потому, что сейчас, согласно данной схеме, я могу передать и `id` поле, что возможно не лучший вариант.

2022-10-31 09:54 UTC, dshemin commented on hw12_13_14_15_calendar/api/EventService.proto
> +  Event event = 2;
У нас в сообщении `event` уже есть поле `id`

2022-10-31 09:54 UTC, dshemin commented on hw12_13_14_15_calendar/api/EventService.proto
> +  int64 updated = 1;
Более верным решением будет, возвращать ошибку, которая произошла. Для клиента нашего АПИ это будет более полезно так, как в текущей реализации не ясно почему мы не смогли обновить.

Возвращать ID обновлённой записи - не самое лучшее решение, мы и так его знаем так, как делали запрос с ним.

2022-10-31 09:54 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +func (s *Storage) CreateEvent(_ context.Context, event model.Event) (model.EventID, error) {
Старайтесь использовать ctx в запросе к БД. Это хорошая практика использовать контекст во всех операциях, которые могут занять некоторое время, чтобы иметь контроль над ними.

2022-10-31 09:54 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/service/crudService.go
> +	uuid, err := cs.crud.CreateEvent(ctx, FromEvent(request.Event))
У нас тут не uuid, лучше не использовать эту аббревиатуру тут, чтобы не сбивать с толку.

2022-10-31 09:54 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
>  package sqlstorage
Лучше не называть это как `sql`  сторадж, а `postgresql` сторадж. Так, как есть много разных SQL баз данных.

2022-10-31 10:36 UTC, Tyrqvir commented on hw12_13_14_15_calendar/api/EventService.proto
> +  Event event = 1;
С одной стороны да, с другой будет будет дубль и при редактировании больше вхождений, я бы вынес конечно в какой нибудь sharedStruct но не знаю как в proto сделать динамический порядок (я про 1, 2, 3 и тд) т.к если наследоваться от структуры то нужно будет его учитывать. Сделаю пока вы сказали

2022-10-31 10:49 UTC, Tyrqvir commented on hw12_13_14_15_calendar/api/EventService.proto
> +  int64 updated = 1;
Так ошибка же возникает на слое "контроллера" , я могу сделать агрегацию ошибок и потом отдать. А UpdateEventResponse я отдаю id в целях отдачи чего то, мб лучше сделать пустой ответ для 204 статус?

2022-10-31 11:14 UTC, Tyrqvir commented on hw12_13_14_15_calendar/api/EventService.proto
> +  Event event = 2;
Переделал на через вложение

2022-10-31 11:15 UTC, Tyrqvir commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +func (s *Storage) CreateEvent(_ context.Context, event model.Event) (model.EventID, error) {
Да я так и сделал в будущих ветках, в рамках этого PR подтянул с hw15 новые правки

2022-10-31 12:27 UTC, Tyrqvir commented on hw12_13_14_15_calendar/api/EventService.proto
> +  int64 updated = 1;
Так ошибка же возникает на слое "контроллера" , я могу сделать агрегацию ошибок и потом отдать. updated это не id а флаг обновлен или нет

2022-10-31 12:29 UTC, Tyrqvir commented on hw12_13_14_15_calendar/internal/server/service/crudService.go
> +	uuid, err := cs.crud.CreateEvent(ctx, FromEvent(request.Event))
Осталось с первой итерации. Поправил

2022-10-31 12:30 UTC, Tyrqvir commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
>  package sqlstorage
Задумка была как раз и назвать абстрактно, чтобы потом при необходимости можно было подменить реализацию не меняя имя пакета

2022-10-31 15:01 UTC, dshemin commented on hw12_13_14_15_calendar/api/EventService.proto
> +  int64 updated = 1;
Будет лучше вернуть всё же ошибку. Если updated - флаг, то лучше его сделать булевым https://developers.google.com/protocol-buffers/docs/proto#scalar

2022-10-31 15:23 UTC, dshemin requested changes

2022-10-31 15:23 UTC, dshemin commented on hw12_13_14_15_calendar/internal/repository/EventRepository.go
> +type EventCrud struct {
Я всё таки не совсем мог понять причину создания `EventCrud`. У нас получается есть такая цепочка `EventRepository` <- `EventCrud` <- `EventService` мне кажется эта прослойка лишняя.

2022-10-31 15:23 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/serverAggregator.go
> +//go:generate protoc -I ../../api --go_out=../../api/eventpb --go_opt=paths=source_relative --go-grpc_out=../../api/eventpb ../../api/EventService.proto
Генерация кода их прото файлов должна быть в GRPC пакете.

2022-10-31 15:23 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/serverAggregator.go
> +	grpc "github.com/Tyrqvir/otus_hw/hw12_13_14_15_calendar/internal/server/grps"
Обратите внимание, у вас неправильно назван пакет grp**s**

2022-10-31 15:23 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/grps/server.go
> +package grps
Должно быть `grpc`

2022-10-31 15:23 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/grps/server.go
> +	listener, err := net.Listen("tcp", s.address)
Лучше использовать https://pkg.go.dev/net#ListenConfig.Listen для того, чтобы связать контекст с "прослушиванием"

2022-10-31 15:23 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/rest/server.go
> +	s.logger.Info("Start http server...")
Тут лучше использовать связку https://pkg.go.dev/net/http#Server.Serve и https://pkg.go.dev/net#ListenConfig.Listen

2022-10-31 16:59 UTC, Tyrqvir commented on hw12_13_14_15_calendar/internal/repository/EventRepository.go
> +type EventCrud struct {
Вы правы, перемудрил, удалил DI на eventCrud и переименовал структуру

2022-10-31 17:05 UTC, Tyrqvir commented on hw12_13_14_15_calendar/internal/server/serverAggregator.go
> +//go:generate protoc -I ../../api --go_out=../../api/eventpb --go_opt=paths=source_relative --go-grpc_out=../../api/eventpb ../../api/EventService.proto
Можете обьяснить почему должна быть? В моей случае у меня есть aggregator для rest + grpc и сгенерированный код относится же к обоим вариантам учитывая gateway

2022-10-31 17:05 UTC, Tyrqvir commented on hw12_13_14_15_calendar/internal/server/grps/server.go
> +package grps
Поправил

2022-10-31 17:16 UTC, Tyrqvir commented on hw12_13_14_15_calendar/internal/server/serverAggregator.go
> +	grpc "github.com/Tyrqvir/otus_hw/hw12_13_14_15_calendar/internal/server/grps"
Поправил

2022-10-31 18:24 UTC, Tyrqvir commented on hw12_13_14_15_calendar/internal/server/grps/server.go
> +	listener, err := net.Listen("tcp", s.address)
Я так сделаю, но пока понимания у меня в этом немного.

2022-10-31 18:29 UTC, Tyrqvir commented on hw12_13_14_15_calendar/internal/server/rest/server.go
> +	s.logger.Info("Start http server...")
А можно по-простому обьяснить чем лучше?

2022-11-01 02:05 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/rest/server.go
> +	s.logger.Info("Start http server...")
Если сделать так, то при отмене контекста, будет завершено прослушивание на порту и завершит работу сервера.

2022-11-01 05:47 UTC, Tyrqvir commented on hw12_13_14_15_calendar/internal/server/rest/server.go
> +	s.logger.Info("Start http server...")
Спасибо

2022-11-01 05:47 UTC, Tyrqvir commented
Что то еще нужно сделать для апрува PR?

2022-11-02 01:23 UTC, dshemin approved these changes

2022-11-02 06:13 UTC, merged