feat: done HW3.
Tyrqvir/otus_hw pull request #4
Opened 2022-06-21 13:09 UTC by Tyrqvir

## Домашнее задание №3 «Частотный анализ»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2022-06-22 04:02 UTC, agneum requested changes
Спасибо за выполненное задание.
Хорошая работа, однако не хватает новых юнит-тестов, поэтому возвращаю решение на доработку

Итого: 5 баллов из 10

При отправке PR желательно не запрашивать ревью сразу у всех проверяющих, т.к выполнять проверку будет только один человек. 
Вполне достаточно отправить ссылку на PR в "Чат с преподавателем" на платформе, проверяющий самостоятельно возьмёт задачу на ревью

2022-06-22 04:02 UTC, agneum commented on hw03_frequency_analysis/top.go
> +	}
switch выглядит избыточно, можно записать в одну строку без потери читаемости

2022-06-22 04:02 UTC, agneum commented on hw03_frequency_analysis/top.go
> +func (p *PairList) transformMapToSlice(mapOfWords *map[string]int) {
Для чего используется указатель на мапу в аргументе?

2022-06-22 04:02 UTC, agneum commented on hw03_frequency_analysis/top.go
> +		}
Можно не проверять наличие слова в мапе и сразу делать инкремент

2022-06-22 07:31 UTC, Tyrqvir commented on hw03_frequency_analysis/top.go
> +	}
Спасибо, согласен. Мне IDE ругался на "The non-bool value 'strings.Compare(firstString, secondString)' (type int) used as a condition". Вот я и заколхозил чтобы реализовать то что хотел, а изаначально конструкция была более шире но потом упразднилась до такого.

2022-06-22 07:35 UTC, Tyrqvir commented on hw03_frequency_analysis/top.go
> +func (p *PairList) transformMapToSlice(mapOfWords *map[string]int) {
В моём понимании, используя указать я сообщаю что не нужно копировать значение при передаче в функцию, для экономии памяти, я если я неправильно понимаю, то можете обьяснить?

2022-06-22 08:19 UTC, Tyrqvir commented on hw03_frequency_analysis/top.go
> +		}
Тут мне не понятно, как я могу сделать инкремент без проверки, в этом же кейсе я тогда не узнаю когда делать инкремент. Можете скинуть пример.

2022-06-22 08:22 UTC, Tyrqvir commented
> Спасибо за выполненное задание. Хорошая работа, однако не хватает новых юнит-тестов, поэтому возвращаю решение на доработку
> 
> Итого: 5 баллов из 10
> 
> При отправке PR желательно не запрашивать ревью сразу у всех проверяющих, т.к выполнять проверку будет только один человек. Вполне достаточно отправить ссылку на PR в "Чат с преподавателем" на платформе, проверяющий самостоятельно возьмёт задачу на ревью

Спасибо за feedback. Принял. Но не понял про unit-test , в 3-ем ДЗ не было написано про доп тесты (во 2-ом было). Скажите тесты на что нужно написать? (только не пишите что на написанный код)

2022-06-22 15:01 UTC, agneum commented on hw03_frequency_analysis/top.go
> +func (p *PairList) transformMapToSlice(mapOfWords *map[string]int) {
Map - ссылочный тип: https://go.dev/blog/maps
Значение мапы - это указатель на структуру `runtime.hmap` (https://go.dev/src/runtime/map.go)
Подробнее: https://dave.cheney.net/2017/04/30/if-a-map-isnt-a-reference-variable-what-is-it

То есть не нужно дополнительно использовать указатель для мапы

2022-06-22 15:02 UTC, agneum commented on hw03_frequency_analysis/top.go
> +		}
```go
mapOfWords[word]++
```

2022-06-22 15:05 UTC, agneum commented
> > Спасибо за выполненное задание. Хорошая работа, однако не хватает новых юнит-тестов, поэтому возвращаю решение на доработку
> > Итого: 5 баллов из 10
> > При отправке PR желательно не запрашивать ревью сразу у всех проверяющих, т.к выполнять проверку будет только один человек. Вполне достаточно отправить ссылку на PR в "Чат с преподавателем" на платформе, проверяющий самостоятельно возьмёт задачу на ревью
> 
> Спасибо за feedback. Принял. Но не понял про unit-test , в 3-ем ДЗ не было написано про доп тесты (во 2-ом было). Скажите тесты на что нужно написать? (только не пишите что на написанный код)

Домашнее задание №3 «Частотный анализ»
> Критерии оценки
>* Пайплайн зелёный - 4 балла
>* **Добавлены новые юнит-тесты** - до 4 баллов
>* Понятность и чистота кода - до 2 баллов

На что ещё можно писать тесты как ни на написанный код?)
Предлагаю рассмотреть различные сценарии, входные данные, граничные случаи, которые не покрыты имеющимися тестами.

2022-06-23 10:31 UTC, agneum approved these changes
Спасибо за правки. 10/10

2022-06-23 13:09 UTC, merged